name: Ejercicio 1

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Saludo personalizado
        run: echo "Hola, mi nombre es Edgar Alejandro Paz Benavides"
      
      - name: Step 2 - Mostrar fecha y hora
        run: date
      
      - name: Step 3 - Mostrar sistema operativo
        run: echo "Sistema operativo:$RUNNER_OS"